### ISSUE TITLE
Laravel 8 Install Fails

### ISSUE THREAD

**Issue by munsterlander** [rickselby/laravel-gate-cache#13]
Tried installing on a Laravel application that started as Laravel version 6-> 7 -> 8 currently.  Running composer results in:

Problem 1
    - Root composer.json requires rickselby/laravel-gate-cache ^3.2 -> satisfiable by rickselby/laravel-gate-cache[3.2].
    - rickselby/laravel-gate-cache 3.2 requires illuminate/auth 5.5.*|5.6.*|5.7.*|5.8.*|6.*|7.* -> found illuminate/auth[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

With how Laravel split up auth, is there a conflict or am I missing something basic here?

**Comment by rickselby** [comment]
I've not used Laravel since ~5.5ish, and every time I come to test this against a new version I expect it to fail... not this time!
