### ISSUE TITLE
Is this package compatible with Laravel Octane?

### ISSUE THREAD

**Issue by bojmaliev** [rickselby/laravel-gate-cache#36]
I noticed when using Laravel Octane sometimes the user receives gate denied for a gate that should be allowed.

Is there any chance this package mixes the gate results between requests because Octane keeps data between requests. 

Is this package Octane safe?

**Comment by rickselby** [comment]
I'm afraid I've not made any new Laravel projects in a few years and didn't know what Octane was until I just looked it up!

The package does cache quite a lot which could be out of date by future requests if the data is kept around. It certainly wasn't written with this in mind.

I'd say this package is not Octane safe.
